import Utils as u
import ClickItem as clickItem


def waitTimer(timer=u.defultTimer):
    u.waitTimer(timer)


def move_point(fx, fy, tx, ty):
    u.move_point(fx, fy, tx, ty)


def moveUp():
    u.moveUp()


def moveDown():
    u.moveDown()


def moveLeft():
    u.moveLeft()


def moveRight():
    u.moveRight()


# ---------------------

def move41寒风营地UpLevel():
    print("move41寒风营地UpLevel")
    clickItem.click33寒风营地()
    moveRight()
    moveRight()
    moveRight()
    moveDown()
    moveDown()
    moveDown()
    moveRight()
    moveRight()
    moveRight()
    moveDown()
    waitTimer()
    moveDown()
    moveRight()
    moveRight()
    moveRight()
    moveRight()
    moveRight()
    moveRight()
    moveRight()
    moveRight()
    moveRight()
    moveUp()
    waitTimer()
    moveUp()
    moveUp()
    moveUp()
    moveUp()
    moveRight()
    moveRight()
    moveRight()
    moveRight()
    moveRight()
    moveUp()
    moveUp()
    moveUp()
    waitTimer(3)
    moveRight()
    moveRight()
    moveRight()
    moveRight()
    moveRight()
    waitTimer(6)
    moveDown()
    moveDown()
    moveDown()
    moveDown()
    moveDown()
    waitTimer(6)
    moveDown()
    moveDown()
    moveDown()
    moveDown()
    moveRight()
    waitTimer(3)
    moveLeft()
    moveDown()
    moveDown()
    moveDown()
    moveDown()
    moveDown()
    waitTimer(3)
    moveDown()
    moveDown()
    moveDown()
    moveDown()
    waitTimer()


def move42寒风营地UpLevel_Diamond():
    print("move42寒风营地UpLevel_Diamond")
    clickItem.click42北风营地()
    moveLeft()
    moveLeft()
    moveLeft()
    moveDown()
    moveDown()
    moveDown()
    waitTimer(3)
    moveLeft()
    moveLeft()
    moveLeft()
    moveLeft()
    moveLeft()
    waitTimer(3)
    moveLeft()
    moveLeft()
    moveLeft()
    waitTimer(3)
    moveDown()
    moveLeft()
    moveDown()
    moveDown()
    waitTimer(3)
    moveUp()
    moveUp()
    moveUp()
    moveLeft()
    moveLeft()
    waitTimer(3)
    moveUp()
    moveUp()
    moveUp()
    moveUp()
    moveUp()
    moveUp()
    waitTimer(3)
    moveLeft()
    moveLeft()
    moveLeft()
    waitTimer(3)
    moveUp()
    moveUp()
    moveUp()
    moveUp()
    waitTimer(3)
    moveRight()
    moveRight()
    moveUp()
    waitTimer()

def move61寂静山谷UpLevel():
    print("move61寂静山谷UpLevel")
    clickItem.click61寂静山谷()
    moveDown()
    moveDown()
    moveDown()
    waitTimer()
    moveLeft()
    moveDown()
    moveLeft()
    moveLeft()
    moveLeft()
    moveDown()
    moveDown()
    waitTimer(3)
    moveLeft()
    moveLeft()
    moveLeft()
    waitTimer(7)
    moveDown()
    moveLeft()
    moveLeft()
    moveDown()
    moveDown()
    moveLeft()
    moveLeft()
    waitTimer(4)
    moveLeft()
    moveDown()
    moveLeft()
    moveLeft()
    moveLeft()
    moveDown()
    moveLeft()
    waitTimer(4)
    moveDown()
    moveDown()
    moveDown()
    moveRight()
    waitTimer(3)
    moveRight()
    moveRight()
    moveDown()
    moveRight()
    moveRight()
    moveRight()
    waitTimer(3)