import Utils as u
import ClickItem as clickItem


def waitTimer(timer=u.defultTimer):
    u.waitTimer(timer)


def move_point(fx, fy, tx, ty):
    u.move_point(fx, fy, tx, ty)


def moveUp():
    u.moveUp()


def moveDown():
    u.moveDown()


def moveLeft():
    u.moveLeft()


def moveRight():
    u.moveRight()


# ---------------------

def move41寒风营地UpLevel():
    print("move41寒风营地UpLevel")
    clickItem.click33寒风营地()
    moveRight()
    moveRight()
    moveRight()
    moveDown()
    moveDown()
    moveDown()
    moveRight()
    moveRight()
    moveRight()
    moveDown()
    waitTimer()
    moveDown()
    moveRight()
    moveRight()
    moveRight()
    moveRight()
    moveRight()
    moveRight()
    moveRight()
    moveRight()
    moveRight()
    moveUp()
    waitTimer()
    moveUp()
    moveUp()
    moveUp()
    moveUp()
    moveRight()
    moveRight()
    moveRight()
    moveRight()
    moveRight()
    moveUp()
    moveUp()
    moveUp()
    waitTimer(3)
    moveRight()
    moveRight()
    moveRight()
    moveRight()
    moveRight()
    waitTimer(6)
    moveDown()
    moveDown()
    moveDown()
    moveDown()
    moveDown()
    waitTimer(6)
    moveDown()
    moveDown()
    moveDown()
    moveDown()
    moveRight()
    waitTimer(3)
    moveLeft()
    moveDown()
    moveDown()
    moveDown()
    moveDown()
    moveDown()
    waitTimer(3)
    moveDown()
    moveDown()
    moveDown()
    moveDown()
    waitTimer()


def move42寒风营地UpLevel_Diamond():
    print("move42寒风营地UpLevel_Diamond")
    clickItem.click42北风营地()
    moveLeft()
    moveLeft()
    moveDown()
    moveDown()
    waitTimer(1)
    moveLeft()
    moveLeft()
    moveLeft()
    moveLeft()
    waitTimer(1)
    moveLeft()
    moveLeft()
    waitTimer(1)
    moveDown()
    moveLeft()
    moveDown()
    moveDown()
    waitTimer(1)
    moveUp()
    moveUp()
    moveLeft()
    moveLeft()
    waitTimer(1)
    moveUp()
    moveUp()
    moveUp()
    moveUp()
    waitTimer(1)
    moveLeft()
    moveLeft()
    waitTimer(1)
    moveUp()
    moveUp()
    moveUp()
    waitTimer(1)
    moveLeft()
    moveDown()
    moveDown()
    moveDown()
    moveLeft()
    moveLeft()
    moveLeft()
    waitTimer(1)
    moveDown()
    moveDown()
    waitTimer(1)


def move61寂静山谷UpLevel():
    print("move61寂静山谷UpLevel")
    clickItem.click61寂静山谷()
    moveDown()
    moveDown()
    waitTimer(1)
    moveLeft()
    moveDown()
    moveLeft()
    waitTimer(1)
    moveLeft()
    moveDown()
    moveDown()
    waitTimer(1)
    moveLeft()
    moveLeft()
    waitTimer(1)
    moveDown()
    moveLeft()
    moveLeft()
    moveDown()
    waitTimer(1)
    moveDown()
    moveLeft()
    moveLeft()
    waitTimer(1)
    moveLeft()
    moveLeft()
    moveDown()
    moveLeft()  # 到拐角了
    waitTimer(1)

    moveDown()
    moveDown()
    moveRight()
    waitTimer(1)
    moveRight()
    moveRight()
    waitTimer(1)
    moveDown()
    moveRight()
    moveRight()
    waitTimer(1)  # 小亭子

    moveDown()
    moveRight()
    moveRight()
    waitTimer(1)

    moveDown()
    moveDown()
    moveRight()
    waitTimer(1)
    moveDown()
    moveRight()
    moveRight()
    moveDown()
    moveRight()
    waitTimer(1)
    moveRight()
    moveDown()
    moveRight()
    moveRight()
    waitTimer(1)
    moveUp()
    moveRight()
    moveRight()
    moveRight()
    moveRight()
    moveUp()
    moveUp()  #右侧是墓碑
    waitTimer(1)
    moveRight()
    moveRight()
    moveRight()
    moveUp()
    waitTimer(1)
    moveRight()
    moveRight()
    moveUp()
    moveLeft()
    moveUp()
    moveUp()
    waitTimer(1)
    moveUp()
    moveUp()
    moveUp()
    waitTimer(1)


def move63哀嚎营地UpLevel():
    print("move63哀嚎营地UpLevel")
    clickItem.click63哀嚎营地()
    moveUp()
    moveLeft()
    moveUp()
    moveUp()
    moveUp()
    waitTimer(2)
    moveRight()
    moveUp()
    moveUp()
    waitTimer(2)
    moveUp()
    moveUp()
    moveUp()
    moveRight()
    moveRight()
    waitTimer(2)
    moveUp()
    moveUp()
    moveRight()
    moveRight()
    moveDown()
    waitTimer(1)
    moveDown()
    moveRight()
    waitTimer(2)
    moveDown()
    moveDown()
    waitTimer(2)
    moveRight()
    moveRight()
    moveRight()
    moveUp()
    moveRight()
    moveUp()
    moveUp()
    waitTimer(2) # 最右侧

    moveLeft()
    moveLeft()
    moveUp()
    moveLeft()
    moveUp()
    waitTimer(2)

    moveLeft()
    moveLeft()
    moveLeft()
    moveUp()
    waitTimer(2)

    moveLeft()
    moveLeft()
    moveUp()
    moveUp()
    moveLeft()
    moveLeft()
    moveLeft()
    waitTimer(2)
    moveLeft()
    moveDown()
    moveDown()
    moveDown()
    moveLeft()
    moveDown()

    waitTimer(2)
    moveLeft()
    moveLeft()
    moveLeft()
    moveDown()
    waitTimer(2) # 猪

    moveDown()
    moveDown()
    moveLeft()
    waitTimer(2)

    moveLeft()
    moveLeft()
    moveLeft()
    moveUp()
    waitTimer(2)
    moveLeft()
    moveDown()
    moveLeft()
    moveLeft()
    moveUp()
    moveUp()
    moveUp()
    waitTimer(2) # 最左侧

    moveRight()
    moveRight()
    moveUp()
    moveRight()
    moveUp()
    moveRight()
    waitTimer(2)

    moveUp()
    moveRight()
    moveUp()
    moveRight()
    waitTimer(2)
